### PR TITLE
Visual bugs and other edits

### PR DESCRIPTION
**Pull request by tpitre**
- https://jira.wnyc.org/browse/DS-423
- https://jira.wnyc.org/browse/DS-421
- https://jira.wnyc.org/browse/CMS-659
- https://jira.wnyc.org/browse/CMS-670

### CODE REVIEW

**Comment by walsh9** [comment]
Just took a quick look at this branch locally and it looks like the 'Home' template has some margin issues below the logo.

**Comment by tpitre** [comment]
@walsh9 I believe that will be resolved in this PR - https://github.com/nypublicradio/pattern-lab/pull/75/files

**Comment by walsh9** [comment]
Hmm.. I don't see it.  `.c-banner` doesn't show up on the plain 'Home' template in this PR so those changes shouldn't affect this.

**Comment by tpitre** [comment]
@walsh9 Ah, try this - https://nypr.southleft.com/?p=pages-home

I just reverted a part of this PR.

**Comment by walsh9** [comment]
Ah, looks good. Also keeping the banner container around is how implemented things on the front end, so it would be nice if we don't have to change that.  

But I think keeping an empty banner div around might also be the cause of the current spacing issue on section pages on demo (between the category and the brand header) so i'm not sure which is less complicated, keeping the container template or taking it out (when there's no banners)...

**Comment by tpitre** [comment]
@walsh9 It's really your call. I'm happy to adjust in PL to accommodate either decision. I'm not sure of what's all involved on the Ember side to adjust for the markup change.

**Comment by walsh9** [comment]
Basically I'd prefer whatever solution lets us have the correct top margins across all templates with the fewest like, adjacent selector/x-th-child/etc. quasi-hacks. If removing the banner box when no banners are present makes the css more straightforward in that way i have no problem making that template change in the client as well, but if it's not much a difference either way i'd rather leave it.

**Comment by tpitre** [comment]
If this is the way it's been on the live site and already approved, I'm hesitant to remove it now without creating another ticket for it to be properly QA'ed. Let's keep it in for now.

**Pull request merged**
